const express = require('express');
const { authenticateToken } = require('../middleware/auth');

module.exports = function (app, pool) {
    const requireSuperAdmin = async (req, res, next) => {
        const user = req.user;
        if (user && (user.phone === '595994854167' || user.email?.includes('595994854167') || user.is_super_admin)) {
            next();
        } else {
            res.status(403).json({ success: false, error: 'Acceso denegado: Se requiere Super Admin' });
        }
    };

    // GET /api/clients - Listar todos los clientes (usuarios que no son super admin)
    app.get('/api/clients', authenticateToken, requireSuperAdmin, async (req, res) => {
        try {
            const connection = await pool.getConnection();
            try {
                // Obtener clientes, su plan, y estado de conexión (sesión activa)
                // Se asume que 'users' son clientes si no son super admin.
                // Status conectado: Verificar si hay una sesión activa en 'user_sessions' o 'sessions' (en memoria, pero aquí usamos DB session table si existe o la columna last_seen)
                // Usaremos last_seen y una verificación adicional si es posible.
                // Sincronizar sesiones activas que no estén en la tabla users
                // Esto asegura que clientes que ingresaron por QR aparezcan en la lista
                await connection.execute(`
                    INSERT INTO users (name, phone, email, password, role, status, created_at, updated_at)
                    SELECT 
                        CONCAT('Usuario ', phone_number) as name,
                        phone_number, 
                        CONCAT(phone_number, '@whatsapp.local') as email,
                        '$2b$10$AutoGeneratedPasswordHashForSync123' as password,
                        'agent' as role,
                        'active' as status,
                        NOW(),
                        NOW()
                    FROM user_sessions us
                    WHERE us.phone_number NOT IN (SELECT phone FROM users WHERE phone IS NOT NULL)
                    AND us.phone_number IS NOT NULL AND us.phone_number != ''
                    GROUP BY us.phone_number
                `);

                const [clients] = await connection.execute(`
                    SELECT 
                        u.id, u.name, u.email, u.phone, u.status, u.is_blocked, u.last_seen, u.created_at,
                        p.name as plan_name, p.id as plan_id,
                        (SELECT COUNT(*) FROM user_sessions us WHERE us.phone_number = u.phone AND us.is_active = 1) as is_connected
                    FROM users u
                    LEFT JOIN plans p ON u.plan_id = p.id
                    WHERE u.role != 'admin' OR (u.role = 'admin' AND u.phone != '595994854167')
                    ORDER BY u.created_at DESC
                `);

                res.json({ success: true, clients });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error fetching clients:', error);
            res.status(500).json({ success: false, error: 'Error obteniendo clientes' });
        }
    });

    // POST /api/clients/:id/assign-plan - Asignar plan
    app.post('/api/clients/:id/assign-plan', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { plan_id } = req.body;

        try {
            const connection = await pool.getConnection();
            try {
                await connection.execute('UPDATE users SET plan_id = ? WHERE id = ?', [plan_id, id]);
                res.json({ success: true, message: 'Plan asignado correctamente' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error assigning plan:', error);
            res.status(500).json({ success: false, error: 'Error asignando plan' });
        }
    });

    // POST /api/clients/:id/block - Bloquear/Desbloquear
    app.post('/api/clients/:id/block', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { blocked } = req.body; // true or false

        try {
            const connection = await pool.getConnection();
            try {
                await connection.execute('UPDATE users SET is_blocked = ? WHERE id = ?', [blocked ? 1 : 0, id]);
                res.json({ success: true, message: blocked ? 'Cliente bloqueado' : 'Cliente desbloqueado' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error blocking client:', error);
            res.status(500).json({ success: false, error: 'Error actualizando estado de bloqueo' });
        }
    });

    // PUT /api/clients/:id - Editar cliente
    app.put('/api/clients/:id', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { name, email, phone, status } = req.body;

        try {
            const connection = await pool.getConnection();
            try {
                await connection.execute(`
                    UPDATE users 
                    SET name = ?, email = ?, phone = ?, status = ?
                    WHERE id = ?
                `, [name, email, phone, status, id]);

                res.json({ success: true, message: 'Cliente actualizado' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error updating client:', error);
            res.status(500).json({ success: false, error: 'Error actualizando cliente' });
        }
    });

    // DELETE /api/clients/:id - Eliminar cliente
    app.delete('/api/clients/:id', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;

        try {
            const connection = await pool.getConnection();
            try {
                await connection.execute('DELETE FROM users WHERE id = ?', [id]);
                // TODO: Limpiar datos relacionados?
                res.json({ success: true, message: 'Cliente eliminado' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error deleting client:', error);
            res.status(500).json({ success: false, error: 'Error eliminando cliente' });
        }
    });
};
