const express = require('express');
const { authenticateToken } = require('../middleware/auth');
const { hashPassword } = require('../auth-utils');

const { sendPlanExpiryReminderEmail, sendGenericNotificationEmail } = require('../utils/subscriptionEmail');
const { sendWhatsAppReminder, sendGenericWhatsApp } = require('../utils/plan-expiry-scheduler');

module.exports = function (app, pool, sessions) {
    const { requireSuperAdmin } = require('../auth-utils');

    // GET /api/clients - Listar todos los clientes (usuarios que no son super admin)
    app.get('/api/clients', authenticateToken, requireSuperAdmin, async (req, res) => {
        try {
            const connection = await pool.getConnection();
            try {
                // Obtener clientes, su plan, y estado de conexión (sesión activa)
                // Se asume que 'users' son clientes si no son super admin.
                // Status conectado: Verificar si hay una sesión activa en 'user_sessions' o 'sessions' (en memoria, pero aquí usamos DB session table si existe o la columna last_seen)
                // Usaremos last_seen y una verificación adicional si es posible.
                // Sincronizar sesiones activas que no estén en la tabla users
                // Esto asegura que clientes que ingresaron por QR aparezcan en la lista
                await connection.execute(`
                    INSERT INTO users (name, phone, email, password, role, status, created_at, updated_at)
                    SELECT
                        CONCAT('Usuario ', phone) as name,
                        phone,
                        CONCAT(phone, '@whatsapp.local') as email,
                        '$2b$10$AutoGeneratedPasswordHashForSync123' as password,
                        'agent' as role,
                        'active' as status,
                        NOW(),
                        NOW()
                    FROM user_sessions us
                    WHERE us.phone NOT IN (SELECT phone FROM users WHERE phone IS NOT NULL)
                    AND us.phone IS NOT NULL AND us.phone != ''
                    GROUP BY us.phone
                `);

                const [clients] = await connection.execute(`
                    SELECT
                        u.id, u.name, u.email, u.phone, u.status, u.is_blocked, u.last_seen, u.created_at,
                        u.plan_expires_at,
                        p.name as plan_name, p.id as plan_id,
                        (SELECT COUNT(*) FROM user_sessions us WHERE us.phone = u.phone AND us.is_active = 1) as is_connected
                    FROM users u
                    LEFT JOIN plans p ON u.plan_id = p.id
                    WHERE u.role != 'super_admin' AND u.is_super_admin != 1
                    ORDER BY u.created_at DESC
                `);

                res.json({ success: true, clients });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error fetching clients:', error);
            res.status(500).json({ success: false, error: 'Error obteniendo clientes' });
        }
    });

    // POST /api/clients/:id/assign-plan - Asignar plan
    app.post('/api/clients/:id/assign-plan', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { plan_id } = req.body;

        try {
            const connection = await pool.getConnection();
            try {
                // Al asignar el plan, establecemos el vencimiento en 30 días por defecto
                // Sincronizar ambos sistemas de planes: legacy (plan_id, plan_expires_at) y nuevo (subscription_*)
                const [planRows] = await connection.execute('SELECT name FROM plans WHERE id = ?', [plan_id]);
                const planName = planRows.length > 0 ? planRows[0].name : 'Estándar';

                await connection.execute(`
                    UPDATE users SET 
                        plan_id = ?, 
                        plan_expires_at = DATE_ADD(NOW(), INTERVAL 30 DAY),
                        subscription_plan = ?,
                        subscription_status = 'active',
                        subscription_start_date = NOW(),
                        subscription_end_date = DATE_ADD(NOW(), INTERVAL 30 DAY),
                        subscription_days = 30
                    WHERE id = ?
                `, [plan_id, planName, id]);
                res.json({ success: true, message: 'Plan asignado correctamente con vencimiento en 30 días (Sincronizado)' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error assigning plan:', error);
            res.status(500).json({ success: false, error: 'Error asignando plan' });
        }
    });

    // POST /api/clients/:id/assign-sms - Asignar saldo SMS
    app.post('/api/clients/:id/assign-sms', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { amount } = req.body;

        if (amount === undefined || amount === null) {
            return res.status(400).json({ success: false, error: 'La cantidad es obligatoria' });
        }

        try {
            const connection = await pool.getConnection();
            try {
                // 1. Obtener datos del usuario primero (para notificar y verificar)
                const [users] = await connection.execute('SELECT phone, name FROM users WHERE id = ?', [id]);
                if (users.length === 0) {
                    return res.status(404).json({ success: false, error: 'Usuario no encontrado' });
                }
                const user = users[0];

                // 2. Actualizar saldo (Usando COALESCE para evitar problemas con NULL)
                await connection.execute('UPDATE users SET sms_balance = COALESCE(sms_balance, 0) + ? WHERE id = ?', [amount, id]);

                // 3. Notificar vía WhatsApp si tiene sesión activa
                let notificationSent = false;
                if (sessions && user.phone) {
                    // Buscar sesión activa por teléfono
                    // Iterar sobre las sesiones para encontrar la que coincide con el teléfono
                    let activeSessionId = null;
                    let activeSock = null;

                    for (const [sessId, sessInfo] of sessions.entries()) {
                        // Verificar si el teléfono coincide (limpiando caracteres)
                        // A veces el phone en DB es '595981...' y en user_sessions session_id podría ser diferente,
                        // pero idealmente buscamos por el número asociado.
                        // La forma más segura es ver si la sesión está mapeada a este usuario.
                        // Simplificación: Asumimos que session_id o el phone coinciden.

                        // Mejor aproximación: Usar la utilidad que busca sesión por numero si existiera, 
                        // pero aquí iteramos simple.
                        if (sessInfo.sock && sessInfo.sock.user) {
                            const jid = sessInfo.sock.user.id || '';
                            const userPhone = jid.split(':')[0];
                            if (userPhone === user.phone) {
                                activeSessionId = sessId;
                                activeSock = sessInfo.sock;
                                break;
                            }
                        }
                    }

                    if (activeSock) {
                        try {
                            const userJid = `${user.phone}@s.whatsapp.net`;
                            await activeSock.sendMessage(userJid, {
                                text: `📱 *Recarga de SMS Exitosa*\n\nHola *${user.name || 'Cliente'}*, se han acreditado *${amount}* SMS a tu cuenta.\n\nSaldo actual disponible en el panel.`
                            });
                            console.log(`[Assign SMS] ✅ Notificación enviada a ${user.phone}`);
                            notificationSent = true;
                        } catch (msgErr) {
                            console.error(`[Assign SMS] ⚠️ Error enviando notificación a ${user.phone}:`, msgErr.message);
                        }
                    }
                }

                res.json({
                    success: true,
                    message: `Saldo de ${amount} SMS asignado correctamente.${notificationSent ? ' Notificación enviada.' : ''}`
                });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error assigning SMS balance:', error);
            res.status(500).json({ success: false, error: 'Error asignando saldo SMS' });
        }
    });

    // POST /api/clients/:id/block - Bloquear/Desbloquear
    app.post('/api/clients/:id/block', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { blocked } = req.body; // true or false

        try {
            const connection = await pool.getConnection();
            try {
                await connection.execute('UPDATE users SET is_blocked = ? WHERE id = ?', [blocked ? 1 : 0, id]);
                res.json({ success: true, message: blocked ? 'Cliente bloqueado' : 'Cliente desbloqueado' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error blocking client:', error);
            res.status(500).json({ success: false, error: 'Error actualizando estado de bloqueo' });
        }
    });

    // PUT /api/clients/:id - Editar cliente
    app.put('/api/clients/:id', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;
        const { name, email, phone } = req.body;

        if (!name || !email || !phone) {
            return res.status(400).json({ success: false, error: 'Todos los campos son obligatorios' });
        }

        try {
            const connection = await pool.getConnection();
            try {
                let query = 'UPDATE users SET name = ?, email = ?, phone = ?, updated_at = NOW()';
                const params = [name, email, phone];

                console.log('[DEBUG-CLIENTS] Actualizando cliente ID:', id);
                console.log('[DEBUG-CLIENTS] Body:', JSON.stringify(req.body));

                if (req.body.password && req.body.password.trim() !== '') {
                    console.log('[DEBUG-CLIENTS] Se detectó cambio de contraseña. Encriptando...');
                    const hashedPassword = await hashPassword(req.body.password);
                    query += ', password = ?';
                    params.push(hashedPassword);
                } else {
                    console.log('[DEBUG-CLIENTS] NO se envió contraseña nueva o está vacía.');
                }

                if (req.body.plan_expires_at) {
                    query += ', plan_expires_at = ?, subscription_end_date = ?, subscription_status = "active"';
                    params.push(req.body.plan_expires_at);
                    params.push(req.body.plan_expires_at);
                }

                query += ' WHERE id = ?';
                params.push(id);

                console.log('[DEBUG-CLIENTS] Query:', query);
                console.log('[DEBUG-CLIENTS] Params:', params);

                const [result] = await connection.execute(query, params); // Destructure result for info
                console.log('[DEBUG-CLIENTS] Rows affected:', result.affectedRows);

                res.json({ success: true, message: 'Cliente actualizado correctamente' });
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error updating client:', error);
            res.status(500).json({ success: false, error: 'Error actualizando cliente' });
        }
    });

    // DELETE /api/clients/:id - Eliminar cliente
    app.delete('/api/clients/:id', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;

        try {
            const connection = await pool.getConnection();
            try {
                // Primero obtener el phone del usuario para limpiar datos relacionados
                const [user] = await connection.execute('SELECT phone FROM users WHERE id = ?', [id]);

                if (user.length === 0) {
                    return res.status(404).json({ success: false, error: 'Cliente no encontrado' });
                }

                const userPhone = user[0].phone;

                // Iniciar transacción para asegurar que todo se elimine o nada
                await connection.beginTransaction();

                try {
                    // Función helper para eliminar con manejo de errores
                    const safeDelete = async (table, condition, params) => {
                        try {
                            await connection.execute(`DELETE FROM ${table} WHERE ${condition}`, params);
                        } catch (err) {
                            if (err.code !== 'ER_NO_SUCH_TABLE') {
                                throw err; // Re-lanzar si no es error de tabla no existente
                            }
                            console.log(`[ADMIN] Tabla ${table} no existe, omitiendo...`);
                        }
                    };

                    // 1. Eliminar sesiones del usuario
                    if (userPhone) {
                        await safeDelete('user_sessions', 'phone = ?', [userPhone]);
                    }

                    // 2. Eliminar contactos relacionados
                    await safeDelete('contacts', 'session_id = ?', [id]);

                    // 3. Eliminar mensajes
                    await safeDelete('messages', 'session_id = ?', [id]);

                    // 4. Eliminar tableros kanban y sus contactos
                    try {
                        const [boards] = await connection.execute('SELECT id FROM kanban_boards WHERE session_id = ?', [id]);
                        for (const board of boards) {
                            await safeDelete('kanban_contacts', 'board_id = ?', [board.id]);
                        }
                        await safeDelete('kanban_boards', 'session_id = ?', [id]);
                    } catch (err) {
                        if (err.code !== 'ER_NO_SUCH_TABLE') throw err;
                    }

                    // 5. Eliminar campañas
                    await safeDelete('campaigns', 'session_id = ?', [id]);

                    // 6. Eliminar citas
                    await safeDelete('appointments', 'session_id = ?', [id]);

                    // 7. Eliminar grupos locales (si existe la tabla)
                    await safeDelete('local_groups', 'session_id = ?', [id]);

                    // 8. Finalmente eliminar el usuario
                    await connection.execute('DELETE FROM users WHERE id = ?', [id]);

                    // Commit de la transacción
                    await connection.commit();

                    console.log(`[ADMIN] ✅ Cliente ID ${id} eliminado correctamente con todos sus datos relacionados`);
                    res.json({ success: true, message: 'Cliente y todos sus datos eliminados correctamente' });
                } catch (error) {
                    // Rollback en caso de error
                    await connection.rollback();
                    throw error;
                }
            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('[ADMIN] ❌ Error deleting client:', error);
            res.status(500).json({ success: false, error: 'Error eliminando cliente: ' + error.message });
        }
    });

    // POST /api/clients/:id/notify-expiration - Enviar notificación manual
    app.post('/api/clients/:id/notify-expiration', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { id } = req.params;

        try {
            const connection = await pool.getConnection();
            try {
                // Obtener datos del usuario
                const [users] = await connection.execute(`
                    SELECT u.id, u.name, u.email, u.phone, u.plan_expires_at, p.name as plan_name
                    FROM users u
                    LEFT JOIN plans p ON u.plan_id = p.id
                    WHERE u.id = ?
                `, [id]);

                if (users.length === 0) {
                    return res.status(404).json({ success: false, error: 'Usuario no encontrado' });
                }

                const user = users[0];
                let emailSent = false;
                let whatsappSent = false;

                // Enviar Email
                if (user.email && user.email.includes('@') && !user.email.includes('.local')) {
                    emailSent = await sendPlanExpiryReminderEmail(user.email, user.name, user.plan_name || 'Sin Plan', user.plan_expires_at || new Date());
                }

                // Enviar WhatsApp
                if (user.phone) {
                    await sendWhatsAppReminder(user, sessions);
                    whatsappSent = true;
                }

                res.json({
                    success: true,
                    message: `Notificaciones enviadas. Email: ${emailSent ? 'OK' : 'No enviado'}, WhatsApp: ${whatsappSent ? 'Enviado' : 'No enviado'}`
                });

            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error sending manual notification:', error);
            res.status(500).json({ success: false, error: 'Error enviando notificaciones' });
        }
    });

    // POST /api/notifications/bulk - Enviar notificaciones masivas
    app.post('/api/notifications/bulk', authenticateToken, requireSuperAdmin, async (req, res) => {
        const { userIds, message, subject, sendEmail, sendWhatsApp } = req.body;
        console.log(`[BULK-NOTIF] Request received: userIds=${JSON.stringify(userIds)}, sendEmail=${sendEmail}, sendWhatsApp=${sendWhatsApp}`);

        if (!message) {
            console.log('[BULK-NOTIF] ❌ Error: Mensaje vacío');
            return res.status(400).json({ success: false, error: 'El mensaje es obligatorio' });
        }

        if (!sendEmail && !sendWhatsApp) {
            console.log('[BULK-NOTIF] ❌ Error: Ningún canal seleccionado');
            return res.status(400).json({ success: false, error: 'Debe seleccionar al menos un canal de envío (Email o WhatsApp)' });
        }

        try {
            const connection = await pool.getConnection();
            try {
                console.log('[BULK-NOTIF] DB Connection acquired');
                let query = `
                    SELECT u.id, u.name, u.email, u.phone
                    FROM users u
                    WHERE u.role != 'super_admin'
                `;
                const params = [];

                // Si no es "todos", filtrar por IDs
                if (userIds !== 'all' && Array.isArray(userIds) && userIds.length > 0) {
                    query += ` AND u.id IN (${userIds.map(() => '?').join(',')})`;
                    params.push(...userIds);
                } else if (userIds !== 'all') {
                    // Si no es 'all' y no es array válido, error o vacío
                    return res.status(400).json({ success: false, error: 'Selección de usuarios inválida' });
                }

                const [users] = await connection.execute(query, params);
                console.log(`[BULK-NOTIF] Iniciando envío a ${users.length} usuarios.`);

                // Procesar envíos en segundo plano (no bloquear respuesta HTTP si son muchos)
                // O responder con progreso. Aquí responderemos rápido y procesaremos.
                // Para feedback inmediato, mejor procesar async y devolver "En proceso".

                const results = {
                    total: users.length,
                    emailSent: 0,
                    whatsappSent: 0,
                    errors: 0
                };

                // Enviamos respuesta rápida para no timeout
                res.json({ success: true, message: `Procesando envío a ${users.length} usuarios...`, total: users.length });

                // Procesamiento Async
                (async () => {
                    const { sendGenericNotificationEmail } = require('../utils/subscriptionEmail');
                    const { sendGenericWhatsApp } = require('../utils/plan-expiry-scheduler');

                    for (const user of users) {
                        try {
                            // Reemplazar variables en el mensaje
                            let personalizedMessage = message;
                            personalizedMessage = personalizedMessage.replace(/{nombre}/gi, user.name || 'Usuario');
                            personalizedMessage = personalizedMessage.replace(/{email}/gi, user.email || '');
                            personalizedMessage = personalizedMessage.replace(/{phone}/gi, user.phone || '');
                            personalizedMessage = personalizedMessage.replace(/{telefono}/gi, user.phone || '');

                            // Email
                            if (sendEmail && user.email && user.email.includes('@') && !user.email.includes('.local')) {
                                const sent = await sendGenericNotificationEmail(user.email, user.name, subject, personalizedMessage);
                                if (sent) results.emailSent++;
                            }

                            // WhatsApp
                            if (sendWhatsApp && user.phone) {
                                console.log(`[BULK-NOTIF] Intentando enviar WhatsApp a ${user.phone}, sessions disponibles: ${sessions ? sessions.size : 'undefined'}`);
                                const sent = await sendGenericWhatsApp(user, sessions, personalizedMessage);
                                if (sent) {
                                    results.whatsappSent++;
                                    console.log(`[BULK-NOTIF] ✅ WhatsApp enviado a ${user.name} (${user.phone})`);
                                } else {
                                    console.log(`[BULK-NOTIF] ❌ Falló envío WhatsApp a ${user.name} (${user.phone})`);
                                }
                            }
                        } catch (err) {
                            console.error(`[BULK-NOTIF] Error procesando usuario ${user.id}:`, err);
                            results.errors++;
                        }
                        // Pequeña pausa para no saturar
                        await new Promise(r => setTimeout(r, 500));
                    }
                    console.log('[BULK-NOTIF] Proceso completado:', results);
                })();

            } finally {
                connection.release();
            }
        } catch (error) {
            console.error('Error in bulk notification:', error);
            // Si ya respondimos, esto no tendrá efecto en el cliente HTTP, pero loguea
            if (!res.headersSent) {
                res.status(500).json({ success: false, error: 'Error procesando notificaciones' });
            }
        }
    });

};
